#%RAML 1.0
title: Weather API
mediaType: application/json
baseUri: http://localhost:8081/api

/cities:
  get:
    description: Returns the List of Cities for the country passed as parameter.
    queryParameters:
      country:
        description: Specify the country to get the cities for.
        type:        string
        required:    true
        example:     Australia
    responses:
      200:
        body:
          application/json:
  
/weather:
  /{country}:
    /{city}: 
      get:
        description: Returns the Weather for the City of the specified country.
        responses:
          200:
            body:
              application/json: